-- Seed blog posts from frontend mock data
INSERT OR IGNORE INTO blog_posts (id, slug, title, excerpt, content, category, author, published_date, tags, read_time, featured, meta_description, updated_at) VALUES
(1, '74-empresas-chilenas-aumentara-inversion-ia', '74% de empresas chilenas aumentará su inversión en IA', 'Las grandes empresas en Chile están redefiniendo sus operaciones en minería, retail, finanzas y salud con inteligencia artificial. Análisis del ecosistema IA nacional.', '<h2>El panorama actual de la IA en Chile</h2><p>La inteligencia artificial está transformando la forma en que las empresas chilenas operan. Según un reciente estudio, el <strong>74% de las grandes empresas</strong> planea aumentar significativamente su inversión en tecnologías de IA durante los próximos dos años.</p><h2>Sectores líderes en adopción</h2><p>Los sectores que lideran esta transformación son:</p><ul><li><strong>Minería:</strong> Mantenimiento predictivo y optimización de procesos extractivos</li><li><strong>Retail:</strong> Personalización de experiencia de cliente y gestión de inventario</li><li><strong>Finanzas:</strong> Detección de fraude y scoring crediticio automatizado</li><li><strong>Salud:</strong> Diagnóstico asistido por IA y gestión hospitalaria</li></ul><h2>Desafíos y oportunidades</h2><p>A pesar del optimismo, las empresas enfrentan desafíos importantes como la escasez de talento especializado, la calidad de los datos disponibles y la necesidad de marcos regulatorios claros.</p><blockquote>La adopción de IA no es una opción, es una necesidad competitiva para las empresas que quieren liderar en sus respectivos mercados.</blockquote><h2>¿Qué deben hacer las empresas?</h2><p>Las organizaciones que buscan aprovechar el potencial de la IA deben comenzar con un diagnóstico exhaustivo de su madurez tecnológica, definir una estrategia clara y contar con partners especializados que entiendan el contexto local.</p>', 'Industria', 'JhedAi', '2026-01-15', '["IA","Chile","inversión","industria"]', '8 min', 1, 'El 74% de las grandes empresas chilenas planea aumentar su inversión en IA. Análisis completo del ecosistema de inteligencia artificial en Chile.', '2026-01-15T10:00:00Z');

INSERT OR IGNORE INTO blog_posts (id, slug, title, excerpt, content, category, author, published_date, tags, read_time, featured, updated_at) VALUES
(2, 'regulacion-ia-chile-primer-marco-legal', 'Regulación IA Chile: primer marco legal en Latinoamérica', 'El Congreso aprobó el primer marco regulatorio para sistemas de IA en la región. Qué significa para tu empresa.', '<h2>Un hito regulatorio</h2><p>Chile se convierte en el primer país de Latinoamérica en establecer un marco legal específico para la inteligencia artificial. Esta regulación establece principios fundamentales para el desarrollo y uso responsable de sistemas de IA.</p><h2>Principales puntos de la regulación</h2><ul><li><strong>Transparencia:</strong> Las empresas deben informar cuando un sistema de IA toma decisiones que afectan a las personas</li><li><strong>No discriminación:</strong> Los sistemas de IA no pueden perpetuar sesgos injustos</li><li><strong>Responsabilidad:</strong> Se establecen mecanismos claros de responsabilidad ante daños</li><li><strong>Protección de datos:</strong> Se refuerzan los estándares de privacidad en el uso de datos para IA</li></ul><h2>Impacto en las empresas</h2><p>Las empresas que ya utilizan IA deberán adaptarse a los nuevos requisitos. Aquellas que aún no han implementado estas tecnologías tienen la oportunidad de hacerlo desde el inicio con un marco claro.</p>', 'Regulación', 'JhedAi', '2026-01-28', '["regulación","Chile","marco legal","compliance"]', '6 min', 0, '2026-01-28T10:00:00Z');

INSERT OR IGNORE INTO blog_posts (id, slug, title, excerpt, content, category, author, published_date, tags, read_time, featured, updated_at) VALUES
(3, 'tendencias-vision-computacional-industria-2026', 'Tendencias en Visión Computacional para la industria', 'La visión por computador representa un cambio estructural en el enfoque de desarrollo industrial en Chile.', '<h2>La revolución visual de la industria</h2><p>La visión computacional está experimentando una evolución acelerada que promete transformar fundamentalmente las operaciones industriales. Desde la inspección de calidad hasta la seguridad laboral, las aplicaciones son cada vez más sofisticadas y accesibles.</p><h2>Tendencias clave para 2026</h2><ul><li><strong>Edge Computing:</strong> Procesamiento en el borde para latencia ultra-baja en líneas de producción</li><li><strong>Modelos multimodales:</strong> Combinación de visión, texto y audio para análisis más completo</li><li><strong>Detección en tiempo real:</strong> Inspección de defectos a velocidad de línea de producción</li></ul><h2>Aplicaciones en Chile</h2><p>En Chile, las industrias minera, portuaria y agrícola están liderando la adopción de visión computacional con resultados medibles en eficiencia y seguridad.</p>', 'Tendencias', 'JhedAi', '2026-02-05', '["visión computacional","industria","tendencias","2026"]', '5 min', 0, '2026-02-05T10:00:00Z');

INSERT OR IGNORE INTO blog_posts (id, slug, title, excerpt, content, category, author, published_date, tags, read_time, featured, updated_at) VALUES
(4, 'capacitaciones-ia-certificacion-chilevalora', 'Capacitaciones IA con certificación ChileValora', 'Chile lidera la región en preparación de talento IA con 74.30 puntos según el Índice Latinoamericano de IA.', '<h2>La importancia de la certificación</h2><p>La certificación ChileValora en perfiles de inteligencia artificial representa un estándar reconocido por el Estado que valida las competencias de los profesionales en IA. JhedAi es pionera como empresa certificadora en estos perfiles.</p><h2>Perfiles certificables</h2><p>Los 5 perfiles de certificación abarcan desde fundamentos de IA hasta aplicaciones avanzadas en Machine Learning y procesamiento de lenguaje natural, cubriendo las necesidades más demandadas del mercado.</p><h2>Beneficios para las empresas</h2><ul><li>Personal certificado con estándares nacionales</li><li>Mejora en la capacidad de adopción tecnológica</li><li>Ventaja competitiva en licitaciones y proyectos gubernamentales</li></ul>', 'Formación', 'JhedAi', '2026-02-12', '["ChileValora","certificación","capacitación","talento IA"]', '4 min', 0, '2026-02-12T10:00:00Z');

INSERT OR IGNORE INTO blog_posts (id, slug, title, excerpt, content, category, author, published_date, tags, read_time, featured, updated_at) VALUES
(5, 'mantenimiento-predictivo-ia-mineria-chile', 'Mantenimiento predictivo con IA en minería chilena', 'Cómo la inteligencia artificial está reduciendo las paradas no planificadas en operaciones mineras de gran escala.', '<h2>El costo de las paradas no planificadas</h2><p>En la minería chilena, una parada no planificada puede costar millones de dólares por día. El mantenimiento predictivo basado en IA permite anticipar fallas antes de que ocurran.</p><h2>Tecnologías aplicadas</h2><p>Los sistemas combinan sensores IoT, análisis vibracional y modelos de machine learning para predecir con precisión cuándo un equipo necesitará mantenimiento.</p>', 'Industria', 'JhedAi', '2025-12-20', '["minería","mantenimiento predictivo","IoT","Chile"]', '7 min', 0, '2025-12-20T10:00:00Z');

INSERT OR IGNORE INTO blog_posts (id, slug, title, excerpt, content, category, author, published_date, tags, read_time, featured, updated_at) VALUES
(6, 'ia-generativa-documentos-industriales', 'IA Generativa para documentación industrial', 'Automatización de reportes técnicos y análisis documental con modelos de lenguaje adaptados al contexto industrial.', '<h2>El desafío documental</h2><p>Las industrias generan enormes volúmenes de documentación técnica. La IA generativa permite automatizar la creación, revisión y análisis de estos documentos.</p><h2>Aplicaciones prácticas</h2><ul><li>Generación automática de reportes de inspección</li><li>Análisis de contratos y documentos legales</li><li>Resumen ejecutivo de informes técnicos extensos</li></ul>', 'Tendencias', 'JhedAi', '2025-11-15', '["IA generativa","documentación","NLP","automatización"]', '5 min', 0, '2025-11-15T10:00:00Z');

INSERT OR IGNORE INTO blog_posts (id, slug, title, excerpt, content, category, author, published_date, tags, read_time, featured, updated_at) VALUES
(7, 'roi-proyectos-ia-como-medirlo', 'ROI de la IA: cómo medir el retorno real de tus proyectos', 'Métricas y frameworks para evaluar el impacto económico de la inteligencia artificial en tu empresa.', '<h2>Más allá de la promesa tecnológica</h2><p>Medir el ROI de proyectos de IA requiere un enfoque estructurado que considere tanto los beneficios directos como los indirectos de la implementación.</p><h2>Framework de medición</h2><p>Un framework efectivo debe incluir métricas de eficiencia operativa, reducción de costos, mejora en calidad y generación de nuevos ingresos.</p>', 'Industria', 'JhedAi', '2025-10-08', '["ROI","métricas","estrategia","negocio"]', '6 min', 0, '2025-10-08T10:00:00Z');

INSERT OR IGNORE INTO blog_posts (id, slug, title, excerpt, content, category, author, published_date, tags, read_time, featured, updated_at) VALUES
(8, 'etica-ia-empresas-chilenas', 'Ética en IA: guía práctica para empresas chilenas', 'Principios y buenas prácticas para implementar inteligencia artificial de forma ética y responsable.', '<h2>¿Por qué importa la ética en IA?</h2><p>La implementación ética de la IA no es solo una responsabilidad moral, sino una ventaja competitiva y un requisito regulatorio cada vez más relevante.</p>', 'Regulación', 'JhedAi', '2025-09-22', '["ética","IA responsable","gobernanza","Chile"]', '5 min', 0, '2025-09-22T10:00:00Z');

INSERT OR IGNORE INTO blog_posts (id, slug, title, excerpt, content, category, author, published_date, tags, read_time, featured, updated_at) VALUES
(9, 'transformacion-digital-pymes-ia', 'Transformación digital de PyMEs con inteligencia artificial', 'La IA ya no es solo para grandes empresas. Cómo las PyMEs chilenas pueden aprovechar estas tecnologías.', '<h2>IA accesible para PyMEs</h2><p>Los avances en IA generativa y herramientas low-code han democratizado el acceso a la inteligencia artificial, abriendo oportunidades para pequeñas y medianas empresas.</p>', 'Industria', 'JhedAi', '2025-08-10', '["PyMEs","transformación digital","accesibilidad","Chile"]', '6 min', 0, '2025-08-10T10:00:00Z');

INSERT OR IGNORE INTO blog_posts (id, slug, title, excerpt, content, category, author, published_date, tags, read_time, featured, updated_at) VALUES
(10, 'formacion-talento-ia-chile-2026', 'Formación de talento IA: el desafío de Chile para 2026', 'Análisis de la brecha de talento en inteligencia artificial y las estrategias para cerrarla.', '<h2>La brecha de talento</h2><p>Chile enfrenta una creciente demanda de profesionales especializados en IA que supera ampliamente la oferta actual del mercado laboral.</p>', 'Formación', 'JhedAi', '2025-07-05', '["talento","formación","educación","mercado laboral"]', '5 min', 0, '2025-07-05T10:00:00Z');
